version: '3'
services:
  # spreso-main-sign-api: # Sign
  spreso-main-api: # Main
    container_name: "spreso" # Main
    image: spreso:latest # Main
    # container_name: "spreso-sign" # Sign
    # image: spreso-sign:latest # Sign
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
